---
- name: Basic Configuration of Managed System
  hosts: managed_systems
  become: yes
  tasks:
    - name: Create a new user
      user:
        name: 'newuser'
        shell: '/bin/bash'
        create_home: yes

    - name: Disable password authentication in SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        validate: '/usr/sbin/sshd -t -f %s'

    - name: Ensure SSH uses Public Key Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        validate: '/usr/sbin/sshd -t -f %s'

    - name: Restart SSH to apply changes
      service:
        name: ssh
        state: restarted

    - name: Install necessary packages
      apt:
        name: ['vim', 'htop']
        state: present

